### ISSUE TITLE
Thank you for the good work provided by the author, but I am very confused that the author provided two models, and the effect of using the two models to run the same data set is very different.

### ISSUE THREAD

**Issue by 2391134843** [Lion-ZS/GIE#7]
Thank you for the good work provided by the author, but I am very confused that the author provided two models, and the effect of using the two models to run the same data set is very different.
In addition, I carefully compared two models, one is the model in the folder /code and the model in the folder /model. The implementation of these two models is very different, and even in the model in the /code folder I did not see the process of negative sampling. Can the author answer these questions for me? really thankful.

**Comment by Lion-ZS** [comment]
Thank you for your attention. In this paper, we focus on modeling the complex structures in KGs. Due to the fact that different datasets are from various sources, it makes the structures of these datasets divergent from each other (e.g., the number of nodes, edges, and other attributes of the datasets). In this sense, we design models for different datasets based on the main idea of geometry interaction operating on different geometric spaces. The realizations of the main idea are the same in models while there are some slight differences between them to capture the more accurate features of structures. By the way, you can also design the model for your datasets in this framework. In addition, the model in the /code folder conduct KGE by operating the head entity with the assistance of the relation, and computing the score functions between the operated head entity and all candidate tail entities in the training and optimization, then choosing the top-k entities according to the ranks of score functions. In this way, it does not need negative sampling.













At 2023-07-17 10:11:19, "dangerous" ***@***.***> wrote:

Thank you for the good work provided by the author, but I am very confused that the author provided two models, and the effect of using the two models to run the same data set is very different.
In addition, I carefully compared two models, one is the model in the folder /code and the model in the folder /model. The implementation of these two models is very different, and even in the model in the /code folder I did not see the process of negative sampling. Can the author answer these questions for me? really thankful.
